from __future__ import annotations


def render_dashboard() -> str:
    """Minimal image-in, measurement-out interface."""
    return '''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>RadMeasure</title><style>
*{box-sizing:border-box}body{margin:0;background:#f5f7fb;color:#17243b;font:16px/1.5 system-ui,sans-serif}main{max-width:720px;margin:60px auto;padding:0 22px}h1{font-size:34px;margin:0}header p{color:#66748b;margin:8px 0 28px}.card{background:white;border:1px solid #e0e6ee;border-radius:20px;padding:26px;margin-bottom:18px;box-shadow:0 8px 30px #15294a05}label{display:block;font-weight:600;margin-bottom:8px}.upload{border:2px dashed #cbd5e3;border-radius:14px;padding:30px 18px;text-align:center;background:#fafcff;cursor:pointer}.upload span{display:block;color:#6d7c92;font-weight:400;font-size:14px;margin-top:6px}input[type=file]{max-width:100%;margin-top:12px}#preview{display:none;max-width:100%;max-height:300px;margin:18px auto 0;border-radius:10px}select,input[type=password],input[type=text]{width:100%;padding:12px;border:1px solid #cbd5e3;border-radius:10px;background:white;font:inherit;color:inherit}.field{margin-top:22px}button{width:100%;padding:14px;margin-top:24px;border:0;border-radius:12px;background:#2563eb;color:white;font:600 16px system-ui;cursor:pointer}button:disabled{opacity:.55;cursor:wait}details{margin-top:16px;color:#758096;font-size:13px}summary{cursor:pointer}details input{margin-top:8px}#result{display:none}h2{font-size:20px;margin:0 0 12px}.angles{display:flex;gap:16px}.angle{flex:1;padding:20px;background:#f1f7ff;border-radius:12px}.angle span{display:block;color:#64748b}.angle strong{font-size:36px;color:#1d4ed8}.review h2{color:#9a5b12}.review{border-color:#f1d2a0;background:#fffbf3}#reason{margin:0;color:#58677e}.note{font-size:12px;color:#8490a3;text-align:center}#status{margin:12px 0 0;color:#65748a;font-size:14px} @media(max-width:500px){main{margin-top:30px}.card{padding:20px}}
</style></head><body><main>
<header><h1>RadMeasure</h1><p>Upload a radiograph. Get angles or a review recommendation.</p></header>
<form id="form" class="card">
<label class="upload" for="image">Upload image<span>JPEG, PNG, or DICOM</span><input id="image" type="file" accept="image/jpeg,image/png,.dcm,application/dicom" required><img id="preview" alt="Uploaded radiograph preview"></label>
<div class="field"><label for="api">Measurement API</label><select id="api"><option value="openai">GPT (OpenAI)</option><option value="claude">Claude (Anthropic)</option><option value="gemini">Gemini (Google)</option></select></div>
<div id="providerFields" class="field"><label for="model">Model ID</label><input id="model" type="text" placeholder="Enter a vision model ID from your account"><label for="providerKey" style="margin-top:14px">API Key</label><input id="providerKey" type="password" autocomplete="off" placeholder="API key for the selected provider"><p class="note">Your image is sent to the selected provider. The key is saved on this server for this job, separate from its results.</p></div>
<details><summary>Connection settings</summary><label for="key">App access key</label><input id="key" type="password" value="operator-local" autocomplete="off"></details>
<button id="run" type="submit">Measure angles</button><p id="status" role="status"></p>
</form>
<section id="result" class="card" aria-live="polite"><h2 id="heading"></h2><div id="angles" class="angles"></div><p id="reason"></p></section>
<p class="note">Research demo</p>
</main><script>
const $=id=>document.getElementById(id);let imageURL=null;
$('image').onchange=()=>{if(imageURL)URL.revokeObjectURL(imageURL);$('preview').style.display='none';$('result').style.display='none';const f=$('image').files[0];if(f&&f.type.startsWith('image/')){imageURL=URL.createObjectURL(f);$('preview').src=imageURL;$('preview').style.display='block'}};
$('preview').onerror=()=>{$('preview').style.display='none'};
async function api(path,options={}){const response=await fetch(path,options);const data=await response.json();if(!response.ok)throw new Error(response.status===401?'Check the app access key in Connection settings.':response.status===403?'This access key cannot perform this action.':typeof data.detail==='string'?data.detail:'The request could not be completed.');return data}
let apiProfiles=[];
function selectProvider(){const p=apiProfiles.find(p=>p.id===$('api').value);$('providerFields').style.display=p?.accepts_key?'block':'none';$('model').value=p?.model||'';$('providerKey').value='';$('model').required=!!p?.accepts_key;$('providerKey').required=!!p?.accepts_key&&!p?.configured;$('providerKey').placeholder=p?.configured?'Leave blank to use the server key':'API key for '+(p?.label||'the selected provider')}
$('api').onchange=selectProvider;
api('/v1/measurement-apis').then(data=>{apiProfiles=data.apis;$('api').replaceChildren();for(const p of data.apis){const o=document.createElement('option');o.value=p.id;o.textContent=p.label;$('api').append(o)}selectProvider()}).catch(()=>{$('status').textContent='API list unavailable. Check the server connection.'});
const reasons={provider_authentication_failed:'The selected provider rejected the API key. Check the key and its permissions.',provider_rate_limited:'The selected provider returned a rate or quota limit. Automatic measurement is unavailable.',provider_request_failed:'The selected provider could not complete the request. Check the model ID and provider availability.',dual_path_models_or_policy_unavailable:'The selected API or landmark model is not configured. Automatic measurement is unavailable.',large_disagreement:'The two models disagree too much. A human should check the image and measurement.',measurement_checks_failed:'The image or measurement did not pass verification. A human should check it.',repair_budget_exhausted:'The models still disagree after the allowed rechecks.',repair_not_authorized:'An automatic recheck is not available for this measurement.',invalid_request_or_policy:'The measurement configuration could not be validated.'};
function showResult(job){$('result').style.display='block';$('angles').replaceChildren();$('reason').textContent='';$('result').classList.remove('review');const result=job.result||{},routing=result.routing||{},m=result.measurements||{};if(job.status==='completed'&&routing.decision==='KEEP'&&['HVA','IMA'].every(n=>Number.isFinite(m[n]))){$('heading').textContent='Measurement complete';for(const name of ['HVA','IMA']){const box=document.createElement('div');box.className='angle';const label=document.createElement('span');label.textContent=name;const value=document.createElement('strong');value.textContent=m[name].toFixed(1)+'°';box.append(label,value);$('angles').append(box)}}else{$('result').classList.add('review');$('heading').textContent='Human review';$('reason').textContent=reasons[routing.reason]||'Automatic measurement could not be completed. A human should review this image.'}}
$('form').onsubmit=async event=>{event.preventDefault();const file=$('image').files[0];if(!file)return;$('run').disabled=true;$('image').disabled=true;$('api').disabled=true;$('result').style.display='none';$('status').textContent='Uploading image…';try{const body=new FormData();body.append('file',file);body.append('api_profile',$('api').value);if(apiProfiles.find(p=>p.id===$('api').value)?.accepts_key){body.append('model',$('model').value);body.append('provider_key',$('providerKey').value)}const headers={'x-api-key':$('key').value,'idempotency-key':crypto.randomUUID()};let data=await api('/v1/uploads',{method:'POST',headers,body});$('providerKey').value='';let job=data.job;const start=Date.now();while(['queued','running'].includes(job.status)){$('status').textContent=job.status==='queued'?'Waiting for measurement…':'Measuring and checking…';if(Date.now()-start>300000)throw new Error('Measurement is still pending. Please try again later.');await new Promise(r=>setTimeout(r,700));job=await api('/v1/jobs/'+encodeURIComponent(job.job_id),{headers:{'x-api-key':headers['x-api-key']}})}$('status').textContent='';showResult(job)}catch(error){$('status').textContent=error.message}finally{$('run').disabled=false;$('image').disabled=false;$('api').disabled=false}};
</script></body></html>'''
