from __future__ import annotations


def render_dashboard() -> str:
    """Return a zero-build portfolio UI served by the FastAPI application."""
    return """<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>RadMeasure</title><style>
:root{color-scheme:dark;--bg:#08111f;--card:#111d30;--line:#263854;--ink:#eaf2ff;--muted:#9eb0c9;--cyan:#4de2c5;--amber:#ffc66d}
*{box-sizing:border-box}body{margin:0;font:15px/1.55 ui-sans-serif,system-ui;background:radial-gradient(circle at 80% 0,#173157 0,transparent 35%),var(--bg);color:var(--ink)}
main{max-width:1080px;margin:auto;padding:48px 24px}h1{font-size:clamp(34px,6vw,64px);line-height:1;margin:12px 0}.eyebrow,.metric b{color:var(--cyan);letter-spacing:.08em}.sub{color:var(--muted);max-width:720px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:14px;margin:28px 0}.card{background:#111d30dd;border:1px solid var(--line);border-radius:14px;padding:18px}.metric b{font-size:26px;display:block}.controls{display:flex;gap:10px;flex-wrap:wrap}input,button{border:1px solid var(--line);border-radius:9px;padding:11px 14px;background:#0b1627;color:var(--ink)}input{flex:1;min-width:240px}button{background:var(--cyan);color:#05201b;font-weight:700;cursor:pointer}pre{white-space:pre-wrap;max-height:520px;overflow:auto;color:#cfe1fa}.tag{display:inline-block;padding:4px 8px;border:1px solid var(--line);border-radius:99px;color:var(--amber)}
</style></head><body><main>
<div class="eyebrow">VERIFIABLE MULTIMODAL EXECUTION</div><h1>RadMeasure</h1>
<p class="sub">Protocol-defined radiographic measurement with deterministic geometry, bounded verification, persisted trajectories, and lineage-aware replay. Research and portfolio demonstration only.</p>
<div class="grid"><div class="card metric"><b>176</b>persisted evaluation cases</div><div class="card metric"><b>3.56°</b>HVA artifact MAE</div><div class="card metric"><b>2.13°</b>IMA artifact MAE</div><div class="card metric"><b>REST + MCP</b>shared typed tool boundary</div></div>
<section class="card"><span class="tag" id="mode">loading backend…</span><h2>Run auditable workflow</h2><div class="controls"><input id="key" type="password" placeholder="API key" value="operator-local" aria-label="API key"><input id="image" value="demo-foot-001" aria-label="Image ID"><input id="question" value="Measure HVA and IMA with supporting evidence" aria-label="Question"><button id="run">Analyze</button></div><pre id="output">Select Analyze to inspect measurements, citations, provenance, and per-tool latency.</pre></section>
<section class="card" style="margin-top:14px"><span class="tag">LIVE IMAGE + HUMAN REVIEW</span><h2>Upload and review</h2>
<div class="controls"><input id="upload" type="file" accept="image/jpeg,image/png,.dcm"><button id="uploadRun">Upload & infer</button><a href="http://127.0.0.1:3000" target="_blank" style="color:var(--cyan);padding:10px">Open OHIF</a></div>
<div class="controls" style="margin-top:10px"><input id="reviewKey" type="password" value="reviewer-local" placeholder="Reviewer API key"><input id="reviewJob" placeholder="Job ID"><input id="hva" type="number" step="0.1" placeholder="Corrected HVA"><input id="ima" type="number" step="0.1" placeholder="Corrected IMA"><button id="approve">Approve</button><button id="reject" style="background:var(--amber)">Reject</button></div>
<pre id="reviewOutput">Upload a de-identified JPEG/PNG, or DICOM (direct identifiers are removed before persistence).</pre></section>
<section class="card" style="margin-top:14px"><span class="tag">OBSERVABILITY + REPLAY</span><h2>Inspect execution lineage</h2>
<div class="controls"><input id="traceKey" type="password" value="viewer-local" placeholder="Viewer API key"><input id="traceId" placeholder="Trace ID"><input id="traceJob" placeholder="Completed job ID"><button id="loadTrace">Load trace</button><button id="replay" style="background:var(--amber)">Replay inputs</button></div>
<pre id="traceOutput">Run a workflow, then inspect its persisted events or create a lineage-linked replay.</pre></section>
</main><script>
const out=document.querySelector('#output'), mode=document.querySelector('#mode');
fetch('/v1/capabilities').then(r=>r.json()).then(x=>mode.textContent=x.mode).catch(()=>mode.textContent='backend unavailable');
fetch('/v1/cases?limit=1').then(r=>r.json()).then(x=>{if(x.cases?.length)document.querySelector('#image').value=x.cases[0]});
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
document.querySelector('#run').onclick=async()=>{out.textContent='Queued…';const idem=crypto.randomUUID(),trace=crypto.randomUUID(),apiKey=document.querySelector('#key').value,auth={'x-api-key':apiKey};const body={image_id:document.querySelector('#image').value,question:document.querySelector('#question').value,top_k:3};const submitted=await fetch('/v1/jobs',{method:'POST',headers:{...auth,'content-type':'application/json','idempotency-key':idem,'x-request-id':trace},body:JSON.stringify(body)}).then(r=>r.json());if(!submitted.job){out.textContent=JSON.stringify(submitted,null,2);return}let job=submitted.job;document.querySelector('#traceId').value=trace;document.querySelector('#traceJob').value=job.job_id;while(['queued','running'].includes(job.status)){out.textContent=JSON.stringify(job,null,2);await sleep(300);job=await fetch('/v1/jobs/'+job.job_id,{headers:auth}).then(r=>r.json())}out.textContent=JSON.stringify(job,null,2)};
const reviewOut=document.querySelector('#reviewOutput');
async function poll(job,apiKey){while(['queued','running'].includes(job.status)){reviewOut.textContent=JSON.stringify(job,null,2);await sleep(400);job=await fetch('/v1/jobs/'+job.job_id,{headers:{'x-api-key':apiKey}}).then(r=>r.json())}reviewOut.textContent=JSON.stringify(job,null,2);document.querySelector('#reviewJob').value=job.job_id;if(job.result?.measurements){document.querySelector('#hva').value=job.result.measurements.HVA;document.querySelector('#ima').value=job.result.measurements.IMA}}
document.querySelector('#uploadRun').onclick=async()=>{const file=document.querySelector('#upload').files[0];if(!file){reviewOut.textContent='Choose an image first.';return}const form=new FormData();form.append('file',file);const key=document.querySelector('#key').value;const data=await fetch('/v1/uploads',{method:'POST',headers:{'x-api-key':key,'idempotency-key':crypto.randomUUID()},body:form}).then(r=>r.json());if(data.job)poll(data.job,key);else reviewOut.textContent=JSON.stringify(data,null,2)};
async function decide(decision){const id=document.querySelector('#reviewJob').value,key=document.querySelector('#reviewKey').value;const body={decision,notes:'Reviewed in RadMeasure dashboard'};if(decision==='approve')body.corrected_measurements={HVA:Number(document.querySelector('#hva').value),IMA:Number(document.querySelector('#ima').value)};const job=await fetch('/v1/jobs/'+id+'/review',{method:'POST',headers:{'x-api-key':key,'content-type':'application/json'},body:JSON.stringify(body)}).then(r=>r.json());reviewOut.textContent=JSON.stringify(job,null,2)}
document.querySelector('#approve').onclick=()=>decide('approve');document.querySelector('#reject').onclick=()=>decide('reject');
const traceOut=document.querySelector('#traceOutput');
document.querySelector('#loadTrace').onclick=async()=>{const id=document.querySelector('#traceId').value,key=document.querySelector('#traceKey').value;const response=await fetch('/v1/traces/'+encodeURIComponent(id),{headers:{'x-api-key':key}});traceOut.textContent=JSON.stringify(await response.json(),null,2)};
document.querySelector('#replay').onclick=async()=>{const id=document.querySelector('#traceJob').value,key=document.querySelector('#key').value,trace=crypto.randomUUID();const response=await fetch('/v1/jobs/'+encodeURIComponent(id)+'/replay',{method:'POST',headers:{'x-api-key':key,'idempotency-key':crypto.randomUUID(),'x-request-id':trace}});const data=await response.json();if(data.job){document.querySelector('#traceJob').value=data.job.job_id;document.querySelector('#traceId').value=data.replay_of_trace_id||trace}traceOut.textContent=JSON.stringify(data,null,2)};
</script></body></html>"""
